# Check out https://docs.codemagic.io/yaml/building-a-react-native-app/ for more information
# Please review and update values

workflows:
    react-native-android:
        name: React Native Android
        max_build_duration: 120
        instance_type: mac_mini
        environment:
            vars:
                GCLOUD_SERVICE_ACCOUNT_CREDENTIALS: Encrypted(Z0FBQUFBQmc3bDR0X0tWMDRISVg0NS1xXzlRMGU3M2VsNUZ0MFpMNFQwdFRtY1QySGMzdWdaMTN0MFFMeERYSDdrc2x0V2RFdmtVVlFQUEdSUi10TjFVZi1MYl9hS2dYV2ZBTTNpSGhqQzdqNHIxQUhDeVp1UDV0TDZXR0toNHkyNHRTbF9IVE1BRGQ=) # <-- Put encrypted CONTENTS of your Gloud crendentials file here
                PACKAGE_NAME: "com.kasunv.codeMagicTest" # <-- Put your package name here e.g. com.domain.myapp
                CM_KEYSTORE: Encrypted(MIIKwAIBAzCCCmoGCSqGSIb3DQEHAaCCClsEggpXMIIKUzCCBboGCSqGSIb3DQEHAaCCBasEggWnMIIFozCCBZ8GCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFMoq2CbHCpyqIYsTEXRh7esVk0W7AgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQVCtaMwm3DEp70UTzRcBtbASCBNArAPhGEUQMUevqvG9Tl7OymSX+d0aRYYoubSCVl9csXUm4SUCe7IK8rAYEiPs+OogYcntH3+ADU9dj40ks8rBlRiUbBR/gVHzoGfUrHHL95N67vSKWZjPBSiZRiSQveKmCWLNqBt4r1bbSBRs1Ir7BRS2+gc1hCrny37RijsrWRTMl3JDhQ1W/fT/8Q4jFmQX63eBsMPTfKgH4mKqBvD13jQmCuJNkyyZYl4F+HNhCJV1uVrycMUF5YbElxy/OzQpxooaoZn0gTsyLHxQiEZuy8YgimeCd9uibka36CuO0gy2wZN+LTBxM0SHl1A1+QlDKpYbUGWkR8KAek2kJ67hiQxqQVsIikTnCGmT3hrONuST63B/LvG1n0qf4YHAFoKZnmOH4sG7FXaX6Iseb/F6Dmwzet13C/ZS+9fQJri3U1GnmuX/AovJlGfTKDkq2SoNwyKzP+JAQ9izFIVigy6sLA9uGZbPDFoxoX2ei9yIK83H8V9aVmIkuqHbV3e1LusNLxi/Lb6LFZJMeLtIyIpdolHAQoUisJpKzZDg6xJr3ITU35bJ4HgS+8mdgnmm6IH8ahEqb4/7FFVtqZYKxxGVHvE117foHKYZXC6EuezankPaBlexm1mBiVb/lyajZSHI5y10N9SXobSGyL3Kb0Lrm8rVHcDwG7UZd2GbIXnC4XPw2QzIpIP1n/cd/cZwNsUGm99OLee5uPKT8VPSglqUvOQFl0sO/+C7JdGncvFIJWamHyH/b9nQUN/v5JMotsMm0HHoYlSMrn5NHP6fhlvTojJX2p/bBbz5MxpzCUZL5nmvKyHP0DnM7cXDo3ZlDvMG6dGnVLgEJCSM2p3e6FwNfVUyRWOr5hGpWE3VoROU+wCUMDoR2Az0Ex62WVORpsCilQYSVJVdugd7ldy7mA18wrnlqT7qqcV+oor3P4YIyKl7tNIrO6Al5gRskiLt8cxY/zZWIpsOUblKdB19um2PIqvRlPwMxb9OuBh7Y4uSKk1BcybQ/4aBgd9wSh4bwQKIqP7mrCNvQum2ROPSAb8iVBV2c8Wj5x2Y7nbAyMcLZQQHT59D1XCHK64F6zWP6S7VKuZsFswG5V4D/HI4ad9rYEpcSl8yeyNmltj7ypY2bGK1HfEbRFxBrQpMLsCh3jFL84WYqYTkQAA63RoyQ9mOTZgaCxWoglwv+x6e/9jWgoGqPuhcacgZcqN+uzghHlg9Wsmh7tJEGiFqz+4I3mVAKQmOsx8HbKivmbZO2odcWPQIL3s1MLQbAYQjxTRbuKcKLF5dcqLwzZusidb6Hwozq3UzTurp7iDHDEL62ll9QWNPkCJHYl5gl0TvjPS/gNO9XixGrcIJP2OgGXU1ugLXf0CXbUKI9n4YK+Tqnm2QjGNtQQUDEeZDUZU7wkKyJvk6pmAxcBOcV/f5skriMjqsNmlCJ4RPSD9DtLZbqYxMpIpVu1EgdZ9cMwe2p5wrV/mj9rc+Y/9+wkXTSkkXm8a7HtxkSl92w0qO7EP+h6BTYrVwsWNqUCHV8o7WztmnTBg5NttVhY5z5sgSlb80VbZTJhfgzNQ23NdS1O9asA7R8veRHGVP6hQtLLQZFoh9J02d0bt+/C/zlYb5AfoN/GaykRn1pVY1oWqXnXDkMdF5AdDFMMCcGCSqGSIb3DQEJFDEaHhgAbQB5AC0AawBlAHkALQBhAGwAaQBhAHMwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTYyNjE3NzYzMDg1MjCCBJEGCSqGSIb3DQEHBqCCBIIwggR+AgEAMIIEdwYJKoZIhvcNAQcBMGYGCSqGSIb3DQEFDTBZMDgGCSqGSIb3DQEFDDArBBQDJAmW9RJch+X9sP/tFK8tlzuRcAICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEED/nzFi3dmYqwOoMl7P2BKSAggQA8+1jWiNKoEng+6ZOV3b/XNxix5mVyFUK/U8fry+lPkoRXYpRbPwZZgTVOGqRY3/T1BuYZ3x0Ol7G11NHpFlRO/azNuJxvMm7iBZIfnuq8faR9pxT/j/zyy1BNVlFM8Zf5THvVEZ0gPwQZwgWXVX6YqkwfOQTaSZTWzM2dPuzlaPqqpnyr0pCYp/rLJUhEi7mOta0Uj3Ich3xE/YbidD90KwBwB9cBLkQI+fds0Il7mYMNoa0Y81JtBxz6akBA/JNt6GR9TFYVNmR5rL4BjvPiQYVoe+oPBbd1cl39V7Y944DaVqsBL4AmaB5E09AE4HqU8W37qWcrZRFx+IXfMM4B3EMKJ1s9JJ1+bOWd25Xz7XONMDQ2UsAbWkzaZimtLWbwgWWpneQjHS3vJCqJI/9/5vKbS+ogjVaqWxbSbQtJzF9p3+tDgOS/I0iWAdi7aKkUAdJkRK7enionhCoKtYwdEPLbRBwfvyzrJrcMLSnXRZPW3N2ZAlJqJgzi86pEm6r5tVzHew/VN8aRaC48odMDo/vCXXr2mguUavQv3Qa0KXRl+r+lRmTpiov73vyJeU34NeUwzOoO02fGvv3Iwt0usmd2XOuoW9Y+m1rwj8AXELmy/EI26UVzL5QMUtaVIwJ+5p73p8aOPgEYmwFSS458JngQXxVTtEk9CNz9xf7zxDnZfSr5jl7MShc7oKdwPk6teYYiG65CEV0ZtN1hrJCJNHUyQeVhUI7V7hr8hBWoIS+REUB3/QD84xPs2BjoW0+ooJ0D3/faZWkxaVRPyomINtEEK855q3bQzejC3jwetK089efP+PA7pwCC/FDU6hOIgAVNgkWCx5GAn4VaR2x0t+T6JyBO4BdY/sLSoB1opHlRPaU1DGrmj92qjy5JoIZXMk2m1zFxlPlgpFknhSloWXfTxCimXSvkgZxjJR2jv/xbBK5ZHzTy6P7q84I7PMBpkB3x1ZC/uVX20JSifZi7NvULu9b4m3WixPHxlgQeVj6ipikLkObFv914goIpVGxSaL9iMq99V0cKpAGDcyXOXCuk1XqjifOkUk7+P0G/ilZuqazfQBseCJEpDVwFFVtQsy6dwnCSt6EWhF08xpSSju789p5DvpmaVRQDv86Wo0pw6UGQ2r6e1WrRHJ1/cGhZozV9nxHtbYKtSMtx24mFWU4bvp++xed4OG/64rwarN/1OSyYLOhWT3iJk5AI61e91RPjE9VyUDPDQ4OueCP8cgLdEzXEPDFLBQscRlhF4ztgjD7f8DMO3UP4eA/D9RBUey6ELFksvFxtkv7HiZgo0LhrMc978Qz3irXerQ+gyyl/kSxk7F8HFWez4XENQNfjnQwbQ9MDxvGrWUPNtB8PzBNMDEwDQYJYIZIAWUDBAIBBQAEIIdJ6n1V26QD0U8EPWi2WeyROU7Tjjk1PntO+tWXsByFBBSXqBMVuzM6Qk3tY3/QEbZ74tAlygICJxA=) # <-- Put your encrypted keystore file here
                CM_KEYSTORE_PASSWORD: Encrypted(Z0FBQUFBQmc3bDJORjRldHNLVUVfSXNscF92Z3BvV2RVcUpMTmJKWXZFUEZjUFQ2clBITmEtNklFaFJOallKamxsbUc1SlBxcW93TUFXWHdJZ2hmdGZyamk4MHN0MV91LWc9PQ==) # <-- Put your encrypted keystore password here
                CM_KEY_ALIAS_PASSWORD: Encrypted(Z0FBQUFBQmc3bDJORjRldHNLVUVfSXNscF92Z3BvV2RVcUpMTmJKWXZFUEZjUFQ2clBITmEtNklFaFJOallKamxsbUc1SlBxcW93TUFXWHdJZ2hmdGZyamk4MHN0MV91LWc9PQ==) # <-- Put your encrypted keystore alias password here
                CM_KEY_ALIAS_USERNAME: Encrypted(Z0FBQUFBQmc3bDNVckhjd2QwcDVwOFhaRTh6Q1ZlRnVRZ0w2RTVCVkxrZXhUcUpSQVZXUXc1cGZ4RzBjWnh2eW5ZQnlxSWVyVWxrWG1aMGI3bzdreXA0N1d0XzdyR192bHc9PQ==) # <-- Put your encrypted keystore alias username here 
            node: latest
        triggering:
            events:
                - push
                - tag
                - pull_request
            branch_patterns:
                - pattern: develop
                  include: true
                  source: true
        scripts:
            - name: Install npm dependencies
              script: |
                npm install
            - name: Set Android SDK location
              script: |
                echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/android/local.properties"
            - name: Set up keystore
              script: |
                    echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
                    cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
                    storePassword=$CM_KEYSTORE_PASSWORD
                    keyPassword=$CM_KEY_ALIAS_PASSWORD
                    keyAlias=$CM_KEY_ALIAS_USERNAME
                    storeFile=/tmp/keystore.keystore
                    EOF               
            - name: Build Android release
              script: |
                # Set environment variable so it can be used to increment build number in android/app/build.gradle
                # Note that tracks can be specified when retrieving latest build number from Google Play, for example:
                # export NEW_BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks=alpha) + 1))
                export NEW_BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME") + 1))
                cd android && ./gradlew assembleRelease
        artifacts:
            - android/app/build/outputs/**/*.apk
        publishing:
            # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
            email:
                recipients:
                    - user_1@example.com
                    - user_2@example.com
                notify:
                  success: true     # To not receive a notification when a build succeeds
                  failure: false    # To not receive a notification when a build fails
            slack: 
              # See the following link about how to connect your Slack account - https://docs.codemagic.io/publishing-yaml/distribution/#slack
              channel: '#channel-name'
              notify_on_build_start: true   # To receive a notification when a build starts
              notify:
                success: true               # To not receive a notification when a build succeeds
                failure: false              # To not receive a notification when a build fails
            google_play:
              # See the following link for information regarding publishing to Google Play - https://docs.codemagic.io/publishing-yaml/distribution/#google-play
              credentials: Encrypted(...) # <-- Put your encrypted google-services.json here
              track: alpha
    react-native-ios:
        name: React Native iOS
        max_build_duration: 120
        instance_type: mac_mini
        environment:
            vars:
                # Env vars for automatic iOS code signing
                # See the following link for more details - https://docs.codemagic.io/code-signing-yaml/signing-ios/
                XCODE_WORKSPACE: "ios/YOUR_WORKSPACE_NAME.xcworkspace" # <-- Put the name of your Xcode workspace here
                XCODE_SCHEME: "YOUR_SCHEME_NAME" # <-- Put the name of your Xcode scheme here
                APPLE_ID: Encrypted(...) # <-- Put you encrypted Apple ID here
                APP_SPECIFIC_PASSWORD: Encrypted(...) # <-- Put your encrypted App Specific Password here. For more information visit: https://support.apple.com/en-us/HT204397
                # https://appstoreconnect.apple.com/access/api
                APP_STORE_CONNECT_ISSUER_ID: Encrypted(...) # <-- Put your App Store Connect Issuer Id here
                APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...) # <-- Put your App Store Connect Key Identifier here
                APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...) # <-- Put your App Store Connect Private Key here
                CERTIFICATE_PRIVATE_KEY: Encrypted(...) # <-- Put your Certificate Private key here
                BUNDLE_ID: "YOUR_BUNDLE_ID_HERE" # <-- Put your Bundle Id here e.g com.domain.myapp
                APP_STORE_APP_ID: 1555555551 # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
            node: latest
            xcode: 12.5
            cocoapods: default
        triggering:
            events:
                - push
                - tag
                - pull_request
            branch_patterns:
                - pattern: develop
                  include: true
                  source: true
        scripts:
            - name: Install npm dependencies
              script: |
                npm install
            - name: Install CocoaPods dependencies
              script: |
                cd ios && pod install
            - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
              script: |
                keychain initialize
            - name: Fetch signing files
              script: |
                # For information about Codemagic CLI commands visit: https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/app-store-connect/README.md
                # For details about the --type paramater below - https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/app-store-connect/fetch-signing-files.md#--typeios_app_adhoc--ios_app_development--ios_app_inhouse--ios_app_store--mac_app_development--mac_app_direct--mac_app_store--mac_catalyst_app_development--mac_catalyst_app_direct--mac_catalyst_app_store--tvos_app_adhoc--tvos_app_development--tvos_app_inhouse--tvos_app_store
                app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
            - name: Use system default keychain
              script: |
                keychain add-certificates
            - name: Increment build number
              script: |
                #!/bin/sh
                set -e
                set -x
                cd $FCI_BUILD_DIR/ios
                # agvtool new-version -all $(($BUILD_NUMBER + 1))
                agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))
            - name: Set up code signing settings on Xcode project
              script: |
                xcode-project use-profiles --warn-only
            - name: Build ipa for distribution
              script: |
                xcode-project build-ipa --workspace "$FCI_BUILD_DIR/ios/$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME" 
        artifacts:
            - build/ios/ipa/*.ipa
            - /tmp/xcodebuild_logs/*.log
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
        publishing:
          # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
          email:
            recipients:
              - user_1@example.com
              - user_2@example.com
            notify:
              success: true     # To not receive a notification when a build succeeds
              failure: false    # To not receive a notification when a build fails
          slack: 
            # See the following link about how to connect your Slack account - https://docs.codemagic.io/publishing-yaml/distribution/#slack
            channel: '#channel-name'
            notify_on_build_start: true   # To receive a notification when a build starts
            notify:
              success: true               # To not receive a notification when a build succeeds
              failure: false              # To not receive a notification when a build fails
          app_store_connect:                 
              apple_id: $APPLE_ID
              password: $APP_SPECIFIC_PASSWORD
    